module.exports = function() {

    var masSimulatorEndpoint = undefined;

    this.getTestGraph = function() {
        return {
            'directed': true,
            'graph': {
                'name': 'Test directed Graph'
            },
            'links': [
                {'source': 0, 'target': 1, 'value':1},
                {'source': 1, 'target': 2, 'value':2},
                {'source': 2, 'target': 3, 'value':2},
                {'source': 3, 'target': 4, 'value':1},
                {'source': 0, 'target': 5, 'value':8},
                {'source': 2, 'target': 5, 'value':8},
                {'source': 3, 'target': 6, 'value':3},
                {'source': 4, 'target': 6, 'value':4},
                {'source': 5, 'target': 4, 'value':2}
            ],            
            'multigraph': false,
            'nodes': [
                {'id': 0},
                {'id': 1},
                {'id': 2},
                {'id': 3},
                {'id': 4},
                {'id': 5},
                {'id': 6}
            ]
        }
    };
    this.getGraph = function() {
        // TODO: proper requesting of masSimulator for graph etc.

        return {
            'directed': false,
            'graph': {
                'name': "Zachary's Karate Club"
            },
            'links': [
                {'source': 0, 'target': 1},
                {'source': 0, 'target': 2},
                {'source': 0, 'target': 3},
                {'source': 0, 'target': 4},
                {'source': 0, 'target': 5},
                {'source': 0, 'target': 6},
                {'source': 0, 'target': 7},
                {'source': 0, 'target': 8},
                {'source': 0, 'target': 10},
                {'source': 0, 'target': 11},
                {'source': 0, 'target': 12},
                {'source': 0, 'target': 13},
                {'source': 0, 'target': 17},
                {'source': 0, 'target': 19},
                {'source': 0, 'target': 21},
                {'source': 0, 'target': 31},
                {'source': 1, 'target': 2},
                {'source': 1, 'target': 3},
                {'source': 1, 'target': 7},
                {'source': 1, 'target': 13},
                {'source': 1, 'target': 17},
                {'source': 1, 'target': 19},
                {'source': 1, 'target': 21},
                {'source': 1, 'target': 30},
                {'source': 2, 'target': 3},
                {'source': 2, 'target': 32},
                {'source': 2, 'target': 7},
                {'source': 2, 'target': 8},
                {'source': 2, 'target': 9},
                {'source': 2, 'target': 13},
                {'source': 2, 'target': 27},
                {'source': 2, 'target': 28},
                {'source': 3, 'target': 7},
                {'source': 3, 'target': 12},
                {'source': 3, 'target': 13},
                {'source': 4, 'target': 10},
                {'source': 4, 'target': 6},
                {'source': 5, 'target': 16},
                {'source': 5, 'target': 10},
                {'source': 5, 'target': 6},
                {'source': 6, 'target': 16},
                {'source': 8, 'target': 32},
                {'source': 8, 'target': 30},
                {'source': 8, 'target': 33},
                {'source': 9, 'target': 33},
                {'source': 13, 'target': 33},
                {'source': 14, 'target': 32},
                {'source': 14, 'target': 33},
                {'source': 15, 'target': 32},
                {'source': 15, 'target': 33},
                {'source': 18, 'target': 32},
                {'source': 18, 'target': 33},
                {'source': 19, 'target': 33},
                {'source': 20, 'target': 32},
                {'source': 20, 'target': 33},
                {'source': 22, 'target': 32},
                {'source': 22, 'target': 33},
                {'source': 23, 'target': 32},
                {'source': 23, 'target': 25},
                {'source': 23, 'target': 27},
                {'source': 23, 'target': 29},
                {'source': 23, 'target': 33},
                {'source': 24, 'target': 25},
                {'source': 24, 'target': 27},
                {'source': 24, 'target': 31},
                {'source': 25, 'target': 31},
                {'source': 26, 'target': 33},
                {'source': 26, 'target': 29},
                {'source': 27, 'target': 33},
                {'source': 28, 'target': 33},
                {'source': 28, 'target': 31},
                {'source': 29, 'target': 32},
                {'source': 29, 'target': 33},
                {'source': 30, 'target': 33},
                {'source': 30, 'target': 32},
                {'source': 31, 'target': 33},
                {'source': 31, 'target': 32},
                {'source': 32, 'target': 33}
            ],
            'multigraph': false,
            'nodes': [
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 0, 'size': 16},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 1, 'size': 9},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 2, 'size': 10},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 3, 'size': 6},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 4, 'size': 3},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 5, 'size': 4},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 6, 'size': 4},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 7, 'size': 4},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 8, 'size': 5},
                {'club': 'Officer', 'color': 'orange', 'id': 9, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 10, 'size': 3},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 11, 'size': 1},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 12, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 13, 'size': 5},
                {'club': 'Officer', 'color': 'orange', 'id': 14, 'size': 2},
                {'club': 'Officer', 'color': 'orange', 'id': 15, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 16, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 17, 'size': 2},
                {'club': 'Officer', 'color': 'orange', 'id': 18, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 19, 'size': 3},
                {'club': 'Officer', 'color': 'orange', 'id': 20, 'size': 2},
                {'club': 'Mr. Hi', 'color': 'purple', 'id': 21, 'size': 2},
                {'club': 'Officer', 'color': 'orange', 'id': 22, 'size': 2},
                {'club': 'Officer', 'color': 'orange', 'id': 23, 'size': 5},
                {'club': 'Officer', 'color': 'orange', 'id': 24, 'size': 3},
                {'club': 'Officer', 'color': 'orange', 'id': 25, 'size': 3},
                {'club': 'Officer', 'color': 'orange', 'id': 26, 'size': 2},
                {'club': 'Officer', 'color': 'orange', 'id': 27, 'size': 4},
                {'club': 'Officer', 'color': 'orange', 'id': 28, 'size': 3},
                {'club': 'Officer', 'color': 'orange', 'id': 29, 'size': 4},
                {'club': 'Officer', 'color': 'orange', 'id': 30, 'size': 4},
                {'club': 'Officer', 'color': 'orange', 'id': 31, 'size': 6},
                {'club': 'Officer', 'color': 'orange', 'id': 32, 'size': 12},
                {'club': 'Officer', 'color': 'orange', 'id': 33, 'size': 17}
            ]
        }
    }

    return this;
};